use_frameworks!

platform :ios, '9.0'

target 'MetaUI_Example' do
  pod 'MetaUI', :path => '../'

  target 'MetaUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
